server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/crowdfunding
    username: crowdfunding
    password: crowdfunding

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb.core: info
    org.hibernate.SQL: debug

app:
  security:
    jwt:
      secret: "CHANGE_ME_TO_LONG_RANDOM_SECRET_CHANGE_ME_TO_LONG_RANDOM_SECRET"
      ttl-minutes: 120